apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubekite
spec:
  selector: 
    matchLabels:
      app: kubekite
  replicas: 1
  template:
    metadata:
      labels:
        app: kubekite
    spec:
      serviceAccountName: kubekite
      containers:
      - name: kubekite
        image: us.gcr.io/sigma-1330/kubekite:1.0
        imagePullPolicy: Always
        env:
          - name: BUILDKITE_API_TOKEN
            valueFrom: {secretKeyRef: {name: buildkite-api, key: token}}
          - name: BUILDKITE_ORG
            value: sigma
          - name: BUILDKITE_PIPELINE
            value: build-sigma-monorepo-master
        resources:
          requests:
            cpu: "0.2"
            memory: "50M"
          limits:
            memory: "100M"
            cpu: "0.4"
